[package]
name = "overseer-server"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
overseer = { path = "../overseer" }
slotmap = "1.0.7"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
whirlwind = "0.1.1"
